## Практика. Прогнозирующие сплит-модели

In [1]:
import warnings
warnings.filterwarnings("ignore", category=UserWarning) 

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import seaborn as sns
sns.set_style("whitegrid")

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score, roc_curve
from sklearn.metrics import confusion_matrix
from sklearn.metrics import RocCurveDisplay

>#### Задание 1
Прочитайте файл `data_flow`.

In [2]:
df = pd.read_csv('data/data_flow.csv')
df

,role,exp_years,projects_count,hours_overtime,edu_level,team_size,client_feedback,certs_count,bonus_rub
0,2,20,16,106,4,9,2.8,6,408672.45
1,1,21,3,343,4,8,1.0,3,403997.39
2,0,1,13,313,2,14,1.1,2,876958.44
3,3,16,16,189,2,17,3.5,3,733683.60
4,2,20,4,306,3,11,1.3,3,355529.40
...,...,...,...,...,...,...,...,...,...
1995,3,16,12,112,3,20,3.5,5,924591.53
1996,3,21,17,30,1,14,4.3,5,937928.00
1997,0,7,3,293,1,9,4.5,2,469633.56
1998,3,25,5,143,1,20,4.1,4,823873.95
1999,0,5,15,140,4,9,2.7,6,989707.24

#### Контекст

Крупная IT-компания «DataFlow» хочет проанализировать, какие факторы влияют на годовую премию сотрудников, чтобы сделать систему бонусов более прозрачной и справедливой. В компании работают специалисты разных профилей, и для каждого направления факторы могут различаться.


#### Датасет
- role — роль сотрудника (0 — разработчик, 1 — аналитик, 2 — тестировщик, 3 — DevOps) (int),
- exp_years — стаж работы в годах (1–25) (int),
- projects_count — количество завершённых проектов за год (2–18) (int),
- hours_overtime — переработки за год (0–400) (int),
- edu_level — уровень образования (1 — среднее, 2 — бакалавр, 3 — магистр, 4 — PhD) (int),
- team_size — размер команды (3–20) (int),
- client_feedback — средняя оценка от клиентов (1.0–5.0) (float),
- certs_count — количество профессиональных сертификаций (0–6) (int).


#### Таргет
- bonus_rub — годовая премия в рублях (50 000–1 500 000) (float). 


#### Бизнес-задача
Моделировать размер премии, чтобы точнее прогнозировать бюджет на бонусы.

>#### Задание 2
Обучите регрессионную модель, которая прогнозирует размер премии. Вычислите ее коэффициент детерминации на test'е.

In [3]:
X = df.drop(columns = ['bonus_rub'])
y = df['bonus_rub']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)#, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [4]:
y_test_pred = model.predict(X_test)

r2_test_sklearn = r2_score(y_test, y_test_pred)
print('r2', r2_test_sklearn)

r2 0.1507217276778653

>#### Задание 3
Посмотрите на коэффициент детерминации, немного поплачьте и подумайте, почему модель такая плохая. Может быть, потому, что разные роли в компании получают бонусы в силу разных причин?

In [5]:
X = df.drop(columns = ['bonus_rub'])
y = df['bonus_rub']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)#, random_state=42)

X_train_0 = X_train.loc[X_train['role'] == 0]
y_train_0 = y_train.loc[X_train_0.index]
model_0 = LinearRegression()
model_0.fit(X_train_0, y_train_0)

X_train_1 = X_train.loc[X_train['role'] == 1]
y_train_1 = y_train.loc[X_train_1.index]
model_1 = LinearRegression()
model_1.fit(X_train_1, y_train_1)

X_train_2 = X_train.loc[X_train['role'] == 2]
y_train_2 = y_train.loc[X_train_2.index]
model_2 = LinearRegression()
model_2.fit(X_train_2, y_train_2)

X_train_3 = X_train.loc[X_train['role'] == 3]
y_train_3 = y_train.loc[X_train_3.index]
model_3 = LinearRegression()
model_3.fit(X_train_3, y_train_3)

LinearRegression()

In [6]:
X_test_0 = X_test.loc[X_test['role'] == 0]
y_test_0 = y_test.loc[X_test_0.index]
y_test_pred_0 = model_0.predict(X_test_0)
print('r2_0 =', r2_score(y_test_0, y_test_pred_0))

X_test_1 = X_test.loc[X_test['role'] == 1]
y_test_1 = y_test.loc[X_test_1.index]
y_test_pred_1 = model_1.predict(X_test_1)
print('r2_1 =', r2_score(y_test_1, y_test_pred_1))

X_test_2 = X_test.loc[X_test['role'] == 2]
y_test_2 = y_test.loc[X_test_2.index]
y_test_pred_2 = model_2.predict(X_test_2)
print('r2_2 =', r2_score(y_test_2, y_test_pred_2))

X_test_3 = X_test.loc[X_test['role'] == 3]
y_test_3 = y_test.loc[X_test_3.index]
y_test_pred_3 = model_3.predict(X_test_3)
print('r2_3 =', r2_score(y_test_3, y_test_pred_3))

r2_0 = 0.9485722798320362
r2_1 = 0.7281283624941008
r2_2 = 0.6348583462984939
r2_3 = 0.9218261316560336

In [7]:
df_y_test_y_pred_0 = pd.DataFrame()
df_y_test_y_pred_0['y_test'] = y_test_0
df_y_test_y_pred_0['y_test_pred'] = y_test_pred_0
df_y_test_y_pred_0

df_y_test_y_pred_1 = pd.DataFrame()
df_y_test_y_pred_1['y_test'] = y_test_1
df_y_test_y_pred_1['y_test_pred'] = y_test_pred_1
df_y_test_y_pred_1

df_y_test_y_pred_2 = pd.DataFrame()
df_y_test_y_pred_2['y_test'] = y_test_2
df_y_test_y_pred_2['y_test_pred'] = y_test_pred_2
df_y_test_y_pred_2

df_y_test_y_pred_3 = pd.DataFrame()
df_y_test_y_pred_3['y_test'] = y_test_3
df_y_test_y_pred_3['y_test_pred'] = y_test_pred_3
df_y_test_y_pred_3

df_y_test_y_pred = pd.concat([df_y_test_y_pred_0, df_y_test_y_pred_1, df_y_test_y_pred_2, df_y_test_y_pred_3])
df_y_test_y_pred

         y_test   y_test_pred
203   618462.45  5.889089e+05
1746  353324.95  4.695294e+05
813   456928.79  4.143342e+05
118   596861.75  6.615716e+05
907   985590.92  1.013665e+06
...         ...           ...
1035  610153.19  5.532977e+05
155   815990.53  8.817903e+05
271   484186.47  4.841864e+05
1246  429685.69  5.030312e+05
1413  781948.65  7.190852e+05

[500 rows x 2 columns]

In [8]:
score = r2_score(df_y_test_y_pred['y_test'], df_y_test_y_pred['y_test_pred'])
score

0.9602337438208928

>#### Задание 4
Прочитайте файл `kinomir`.

In [22]:
df = pd.read_csv('data/kinomir.csv')
df

,tariff_type,age,watch_hours_week,content_completion,device_type,promo_used,support_tickets,friend_referrals,subscription_renew
0,0,45,36.6,0.57,2,0,2,0,0
1,2,24,17.4,0.33,1,1,0,0,0
2,2,52,10.3,0.32,0,0,2,0,0
3,1,72,17.4,0.11,0,0,2,0,1
4,0,45,28.9,0.37,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...
1995,1,71,10.5,0.04,0,1,3,0,1
1996,2,67,16.9,0.24,2,1,4,0,0
1997,0,52,1.6,0.89,0,1,2,0,0
1998,0,69,18.0,0.01,1,0,1,1,0
1999,0,38,23.1,0.20,2,1,0,1,0

#### Контекст
Онлайн-кинотеатр «Kinomir» хочет повысить удержание подписчиков. Аналитики заметили, что пользователи разных тарифных планов ведут себя принципиально различно, и решение о продлении подписки зависит от разных факторов в зависимости от типа тарифа.

#### Датасет

- tariff_type — тип тарифа (0 — базовый, 1 — премиум, 2 — студенческий) (int),
- age — возраст пользователя (18–75) (int),
- watch_hours_week — среднее количество часов просмотра в неделю (0–40) (float),
- content_completion — доля полностью досмотренных фильмов/сериалов (0.0–1.0) (float),
- device_type — тип устройства (0 — смартфон, 1 — ноутбук, 2 — Smart TV) (int),
- promo_used — использовал ли промокод при оформлении (0 — нет, 1 — да) (int),
- support_tickets — количество обращений в поддержку за последние 3 месяца (0–15) (int),
- friend_referrals — привел ли друзей (0 — нет, 1 — да) (int).

#### Таргет
- subscription_renew — продлил ли подписку на следующий месяц (0 — нет, 1 — да) (int). 

#### Бизнес-задача
Предсказывать `subscription_renew`, чтобы применять разные стратегии удержания.

>#### Задание 5
Обучите бинарный классификатор, который прогнозирует продление подписки. Вычислите метрики accurcy, prcision, recall и f1 на test'е.

In [23]:
X = df.drop(columns = ['subscription_renew'])
y = df['subscription_renew']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

model = KNeighborsClassifier()
model.fit(X_train, y_train)

KNeighborsClassifier()

In [24]:
y_test_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_test_pred)
print('accuracy =', accuracy)
precision = precision_score(y_test, y_test_pred)
print('precision =', precision)
recall = recall_score(y_test, y_test_pred)
print('recall =', recall)
f1 = f1_score(y_test, y_test_pred)
print('f1 =', f1)

accuracy = 0.82
precision = 0.6829268292682927
recall = 0.4666666666666667
f1 = 0.5544554455445545

>#### Задание 6
Постройте сплит-модель, используя для разбиения тип тарифа. Вычислите метрики классификации на test'е.

In [25]:
X = df.drop(columns = ['subscription_renew'])
y = df['subscription_renew']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

X_train_0 = X_train.loc[X_train['tariff_type'] == 0]
y_train_0 = y_train.loc[X_train_0.index]
model_0 = KNeighborsClassifier()
model_0.fit(X_train_0, y_train_0)

X_train_1 = X_train.loc[X_train['tariff_type'] == 1]
y_train_1 = y_train.loc[X_train_1.index]
model_1 = KNeighborsClassifier()
model_1.fit(X_train_1, y_train_1)

X_train_2 = X_train.loc[X_train['tariff_type'] == 2]
y_train_2 = y_train.loc[X_train_2.index]
model_2 = KNeighborsClassifier()
model_2.fit(X_train_2, y_train_2)

KNeighborsClassifier()

In [26]:
print('')
X_test_0 = X_test.loc[X_test['tariff_type'] == 0]
y_test_0 = y_test.loc[X_test_0.index]
y_test_pred_0 = model_0.predict(X_test_0)
print('accuracy_0 =', accuracy_score(y_test_0, y_test_pred_0))
print('precision_0 =', precision_score(y_test_0, y_test_pred_0))
print('recall_0 =', recall_score(y_test_0, y_test_pred_0))
print('f1_0 =', f1_score(y_test_0, y_test_pred_0))
print('')
X_test_1 = X_test.loc[X_test['tariff_type'] == 1]
y_test_1 = y_test.loc[X_test_1.index]
y_test_pred_1 = model_1.predict(X_test_1)
print('accuracy_1 =', accuracy_score(y_test_1, y_test_pred_1))
print('precision_1 =', precision_score(y_test_1, y_test_pred_1))
print('recall_1 =', recall_score(y_test_1, y_test_pred_1))
print('f1_1 =', f1_score(y_test_1, y_test_pred_1))
print('')
X_test_2 = X_test.loc[X_test['tariff_type'] == 2]
y_test_2 = y_test.loc[X_test_2.index]
y_test_pred_2 = model_2.predict(X_test_2)
print('accuracy_2 =', accuracy_score(y_test_2, y_test_pred_2))
print('precision_2 =', precision_score(y_test_2, y_test_pred_2))
print('recall_2 =', recall_score(y_test_2, y_test_pred_2))
print('f1_2 =', f1_score(y_test_2, y_test_pred_2))
print('')

accuracy_0 = 0.9794871794871794
precision_0 = 1.0
recall_0 = 0.9310344827586207
f1_0 = 0.9642857142857143

accuracy_1 = 0.9741935483870968
precision_1 = 0.9411764705882353
recall_1 = 0.9411764705882353
f1_1 = 0.9411764705882353

accuracy_2 = 0.9866666666666667
precision_2 = 0.9333333333333333
recall_2 = 1.0
f1_2 = 0.9655172413793104

In [27]:
df_y_test_y_pred_0 = pd.DataFrame()
df_y_test_y_pred_0['y_test'] = y_test_0
df_y_test_y_pred_0['y_test_pred'] = y_test_pred_0
df_y_test_y_pred_0

df_y_test_y_pred_1 = pd.DataFrame()
df_y_test_y_pred_1['y_test'] = y_test_1
df_y_test_y_pred_1['y_test_pred'] = y_test_pred_1
df_y_test_y_pred_1

df_y_test_y_pred_2 = pd.DataFrame()
df_y_test_y_pred_2['y_test'] = y_test_2
df_y_test_y_pred_2['y_test_pred'] = y_test_pred_2
df_y_test_y_pred_2


df_y_test_y_pred = pd.concat([df_y_test_y_pred_0, df_y_test_y_pred_1, df_y_test_y_pred_2])
df_y_test_y_pred

      y_test  y_test_pred
353        0            0
1289       0            0
1273       0            0
938        0            0
1323       0            0
...      ...          ...
715        1            1
1874       0            0
532        0            0
1356       0            0
408        0            0

[500 rows x 2 columns]

In [28]:
accuracy = accuracy_score(df_y_test_y_pred['y_test'], df_y_test_y_pred['y_test_pred'])
print('accuracy = ', accuracy)
precision = precision_score(df_y_test_y_pred['y_test'], df_y_test_y_pred['y_test_pred'])
print('precision = ', precision)
recall = recall_score(df_y_test_y_pred['y_test'], df_y_test_y_pred['y_test_pred'])
print('recall = ', recall)
f1 = f1_score(df_y_test_y_pred['y_test'], df_y_test_y_pred['y_test_pred'])
print('f1 = ', f1)

accuracy =  0.98
precision =  0.9661016949152542
recall =  0.95
f1 =  0.957983193277311

## Домашнее задание

>#### Задание 1
Прочитайте файл `trans_log`.

In [16]:
df = pd.read_csv('data/trans_log.csv')
df

,brand,mileage_km,load_weight,route_type,driver_exp,terrain,speed_avg,temp_outside,fuel_consumption_l_100km
0,2,20725,8.3,0,3,2,79.6,32,31.0
1,2,5111,9.1,2,30,0,61.9,24,34.4
2,3,17739,5.9,2,21,0,56.4,-18,32.3
3,0,22766,9.1,2,28,2,56.2,15,36.3
4,3,17394,19.1,2,27,2,48.5,-7,32.8
...,...,...,...,...,...,...,...,...,...
1995,0,13402,9.1,0,21,2,45.9,35,35.4
1996,0,23517,8.7,1,9,0,64.5,36,30.9
1997,2,7816,21.5,2,2,2,53.1,-13,40.9
1998,3,11518,20.4,2,12,1,49.5,21,33.7
1999,1,15642,15.7,2,9,0,81.3,-4,32.7

#### Контекст
Логистическая компания «TransLog» управляет парком грузовых автомобилей разных марок. Расход топлива сильно различается в зависимости от марки автомобиля, поэтому для каждой марки имеет смысл строить отдельную модель прогноза.

#### Датасет
- brand — марка автомобиля (0 — Scania, 1 — Volvo, 2 — MAN, 3 — Mercedes),
- mileage_km — пробег за месяц (5 000–25 000) (int),
- load_weight — средняя загрузка в тоннах (2.0–24.0) (float),
- route_type — тип маршрута (0 — городской, 1 — трасса, 2 — смешанный) (int),
- driver_exp — стаж водителя в годах (1–30) (int),
- terrain — рельеф местности (0 — равнина, 1 — холмы, 2 — горы) (int),
- speed_avg — средняя скорость за поездку (40–95 км/ч) (float),
- temp_outside — среднесуточная температура воздуха (–25…+40 °C) (int).

#### Таргет
- fuel_consumption_l_100km — расход топлива на 100 км (15.0–45.0) (float).

#### Бизнес-задача
Прогнозировать расход топлива, чтобы оптимизировать заправки, выбирать наиболее экономичные маршруты и планировать техобслуживание.

>#### Задание 2
Обучите регрессионную модель, которая прогнозирует размер премии. Вычислите ее коэффициент детерминации на test'е.

In [17]:
# Код

>#### Задание 3
Постройте сплит-модель, используя для разбиения тип тарифа. Вычислите коэффициент детерминации на test'е.

In [18]:
# Код

>#### Задание 4
Прочитайте файл `fit_zone`.

In [19]:
df = pd.read_csv('data/fit_zone.csv')
df

,membership_type,distance_km,visits_per_week,duration_months,age,gender,personal_goal,late_cancels,churn
0,2,8.7,1.1,22,65,0,1,1,0
1,1,8.2,6.8,9,56,1,0,1,0
2,0,1.2,4.3,9,60,1,0,0,0
3,1,17.7,1.1,37,24,1,0,0,0
4,2,13.7,5.6,4,62,0,1,1,0
...,...,...,...,...,...,...,...,...,...
1995,0,11.3,7.0,27,24,0,1,1,1
1996,2,11.1,5.3,9,47,0,0,2,0
1997,1,14.9,3.4,56,21,0,1,2,1
1998,2,14.2,4.7,8,62,0,1,1,0
1999,0,12.6,1.0,23,29,1,1,0,1

#### Контекст
Сеть фитнес-клубов «FitZone» хочет снизить отток клиентов. Тренировочные программы и мотивация сильно различаются в зависимости от того, в какой группе занимается клиент: индивидуальные тренировки, групповые занятия или свободное посещение.

#### Датасет

- membership_type — тип абонемента (0 — индивид., 1 — групповые, 2 — свободное) (int),
- distance_km — расстояние от дома до клуба (0.5–20.0 км) (float),
- visits_per_week — среднее количество посещений в неделю (0–7) (float),
- duration_months — сколько месяцев клиент уже ходит (1–60) (int),
- age — возраст клиента (18–65) (int),
- gender — пол (0 — муж., 1 — жен.) (int),
- personal_goal — указал ли цель при оформлении (0 — нет, 1 — да) (int),
- late_cancels — количество отмен занятий менее чем за 2 часа за месяц (0–10) (int).


#### Таргет
- churn — прекратил ли посещение в следующем месяце (0 — нет, 1 — да) (int).


#### Бизнес-задача
Предсказывать вероятность оттока, чтобы предлагать персонализированные удерживающие мероприятия.

>#### Задание 5
Обучите бинарный классификатор, который прогнозирует уход клиента. Вычислите метрики accurcy, prcision, recall и f1 на test'е.

In [20]:
# Код

>#### Задание 6
Постройте сплит-модель, используя для разбиения тип абонемента. Вычислите метрики классификации на test'е.

In [21]:
# Код